### ISSUE TITLE
KeyError: 'SLEEPTIME'

### ISSUE THREAD

**Issue by eigentlichich** [marclave/InstaBot#10]
Hey Marclave,
I always get this Error if i start the bot :( can you help?

=================================
            InstaBot             
    Developed by Marc Laventure  
=================================

Liking #huntgram
 YOU LIKED 955809077622088464_964231

Traceback (most recent call last):
  File "/Users/Julian/Documents/InstaBot/InstaBot.py", line 113, in <module>
    like(br, hashtags)
  File "/Users/Julian/Documents/InstaBot/InstaBot.py", line 85, in like
    time.sleep(profile['SLEEPTIME'])
KeyError: 'SLEEPTIME'

**Comment by marclave** [comment]
Can you post your profile please, I believe you input an incorrect sleep time

**Comment by eigentlichich** [comment]
Had to add the line SLEEPTIME: 2 to the profile.yml. Works now.

**Comment by marclave** [comment]
Excellent, I figured it was such.
