### ISSUE TITLE
Scope Likes not found

### ISSUE THREAD

**Issue by corriejgreen** [marclave/InstaBot#11]
https://instagram.com/oauth/authorize/?client_id=INSERT_CLIENTID&redirect_uri=INSERT_REDIRECTURI&response_type=code&scope=likes+basic

The api is vague, this could be the solution for most python scripts but not this one.

OAuthPermissionException request requires scope=likes needs write permissions

Thanks

**Comment by marclave** [comment]
Interesting okay, I dont think this is an issue rather should be implemented. Im going to close this one if you want to implement handling this exception you can, else i will do that soon.

Marc
