### ISSUE TITLE
How can I run the code on Windows?

### ISSUE THREAD

**Issue by ghost** [marclave/InstaBot#16]
Sorry if it sounds silly but I don't have enough knowledge to run the code on Windows.

**Comment by marclave** [comment]
@sergiomoraesj there is no such thing as a silly question, hit the windows button on the button left, search for command prompt... then type in python and let me know if it is installed, if it is please navigate to the directory where the python script is then run the following after completing the readme steps:

```
python Instabot.py
```

**Comment by ghost** [comment]
Thanks for answering so fast, @marclave 

I do have Python installed. I was trying to run the code through Enthought-Canopy. 
I just tried to run it through cmd but I received the following error message:

![instabot error message](https://cloud.githubusercontent.com/assets/4682499/8215095/bad39cf6-14fb-11e5-8f43-071c6ca21f63.jpg)

**Comment by marclave** [comment]
@sergiomoraesj No worries, pleaser re-authorize your application with scope=likes. Let me know if you have any more issues.

**Comment by sergiomoraesj** [comment]
@marclave I do not know how to re-authorize the application with scope=likes.
