### ISSUE TITLE
Some error

### ISSUE THREAD

**Issue by jaguar754** [marclave/InstaBot#6]
It doesnt start. 
# 

```
        InstaBot             
Developed by Marc Laventure  
```
# 

Liking #love
{"meta":{"error_type":"OAuthParameterException","code":400,"error_message":"The access_token provided is invalid."}}SOMETHING WENT WRONG
400
SLEEPING FOR 60 seconds
CURRENTLY LIKED 0 photos

**Comment by praneethkumarpidugu** [comment]
I get the same error and also readme need to be updated
