### ISSUE TITLE
No permissions

### ISSUE THREAD

**Issue by jaguar754** [marclave/InstaBot#7]
{"meta":{"error_type":"OAuthPermissionsException","code":400,"error_message":"This request requires scope=likes, but this access token is not authorized with this scope. The user must re-authorize your application with scope=likes to be granted write permissions."}}SOMETHING WENT WRONG
400

Thats when I run the script.

How to add permissions ?

**Comment by joaoreis81** [comment]
Still with this issue... Any idea?

**Comment by priscila225** [comment]
I think instagram changes the permission policies : https://help.instagram.com/contact/185819881608116
