### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by diegotfcastro** [marclave/InstaBot#9]
castro@castro:~$ cd InstaBot/
castro@castro:~/InstaBot$ ls
hashtags.txt  InstaBot.py~  profile.yml~        README.md
InstaBot.py   profile.yml   PycURL Download.md
castro@castro:~/InstaBot$ python InstaBot.py 
Traceback (most recent call last):
  File "InstaBot.py", line 1, in <module>
    import mechanize, yaml, re, time, sys, pycurl, hmac
ImportError: No module named yaml

**Comment by marclave** [comment]
Hi @diegotfcastro, please refer to the install guide(Most specifically step 3):
```
PyYAML libray is installed [PyYAML download!](pyyaml.org/wiki/PyYAML) V3.11
```
Thanks.

Closing this
